---
title: "statistical-learning"
author: "Rosie Kwon"
date: "2025-11-22"
output: html_document
---

```{r, include = FALSE, message = FALSE, warning = FALSE}
library(tidyverse)

knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```
Load key packages
```{r}
library(tidyverse)
library(glmnet)
library(palmerpenguins)

set.seed(11)
```

Lasso
```{r}
bwt_df = 
  read_csv("data/birthweight.csv") |> 
  janitor::clean_names() |>
  mutate(
    babysex = 
        case_match(babysex,
            1 ~ "male",
            2 ~ "female"
        ),
    babysex = fct_infreq(babysex),
    frace = 
        case_match(frace,
            1 ~ "white",
            2 ~ "black", 
            3 ~ "asian", 
            4 ~ "puerto rican", 
            8 ~ "other"),
    frace = fct_infreq(frace),
    mrace = 
        case_match(mrace,
            1 ~ "white",
            2 ~ "black", 
            3 ~ "asian", 
            4 ~ "puerto rican",
            8 ~ "other"),
    mrace = fct_infreq(mrace),
    malform = as.logical(malform)) |> 
  sample_n(200)
```

Need to do some data processing

```{r}
x = model.matrix(bwt ~ ., bwt_df)[, -1]
y = bwt_df |> pull(bwt)
```

Define some lamdas and fit Lasso for each
```{r}
lambda = 10^(seq(-2, 2.75, 0.1))

lasso_fit = 
  glmnet(x = x, y = y, lambda = lambda)

lasso_cv =
  cv.glmnet(x = x, y = y, lambda = lambda)

lambda_opt = lasso_cv[["lambda.min"]]
```

Plot 1

```{r}
lasso_fit |> 
	broom::tidy() |> 
	select(term, lambda, estimate) |> 
	complete(term, lambda, fill = list(estimate = 0)) |> 
	filter(term != "(Intercept)") |> 
	ggplot(aes(x = log(lambda, 10), y = estimate, group = term, color = term)) + 
	geom_line() + 
	geom_vline(xintercept = log(lambda_opt, 10))
```

Plot 2

```{r}
lasso_cv |> 
  broom::tidy() |> 
  ggplot(aes(x = log(lambda, 10), y = estimate)) +
  geom_point()
```

coefficients from the optimal model 

```{r}
lasso_fit = 
  glmnet(x, y, lambda = lambda_opt)

lasso_fit |> broom::tidy()
```


Clustering
```{r}
pokemon_df =
  read_csv("data/pokemon.csv") |> 
  janitor::clean_names() |> 
  select(hp, speed)
```


```{r}
pokemon_df |> 
  ggplot(aes(x= hp, y = speed))+
  geom_point()
```

Fit kmeans clustering to this dataset

```{r}
kmeans_fit =
  kmeans(x = pokemon_df, centers = 3)
```

```{r}
pokemon_df = 
  broom::augment(kmeans_fit, pokemon_df)
```

```{r}
pokemon_df |> 
  ggplot(aes(x = hp, y = speed, color = .cluster)) + 
  geom_point()
```

```{r}
clusts =
  tibble(k = 2:4) |>
  mutate(
    km_fit = map(k, \(n_clust) kmeans(pokemon_df, centers = n_clust)),
    augmented = map(km_fit, \(fit) broom::augment(x = fit, pokemon_df))
  )

clusts |> 
  select(-km_fit) |> 
  unnest(augmented) |> 
  ggplot(aes(hp, speed, color = .cluster)) +
  geom_point(aes(color = .cluster)) +
  facet_grid(~k)
```



